define({
    "OK": "확인",
    "CANCEL": "취소",
    "DELETE": "삭제",
    "BUTTON_YES": "예",
    "BUTTON_NO": "아니오",
    "ERROR": "에러",
    "ALERT_TITLE" : "알림",
    "ALERT_NO_SEARCH_RESULT": "검색 결과가 없습니다.",
    "ADD_BOOKMARK_TITILE": "북마크 추가",
    "REMOVE_BOOKMARK_TITILE": "북마크 제거",
    "MODIFY_BOOKMARK_TITILE": "북마크 수정",
    "ENTER_TEXT": "내용을 입력하세요",
    "TEXT_INPUT_PLACEHOLDER": "텍스트를 입력하세요",
    "ENTER_SEARCH_WORDS_PLACEHOLDER": "검색어를 입력하세요...",
    "ADD_MEMO_TITILE" : "메모 추가",
    "MODIFY_MEMO_TITILE": "메모 수정",
    "EMPTY": "비어 있음",
    "SELECT_PAGE_TITLE": "페이지 선택",
    "LEFT_PAGE_TITLE": "왼쪽 페이지",
    "RIGHT_PAGE_TITLE": "오른쪽 페이지",
    "REMOVE_ALL_MY_LIBRARY": "보관함을 전부 삭제 하시겠습니까?",
    "ERROR_NOT_VALID_PAGE_NUMBER" : "{0} 페이지는 유효한 페이지 번호가 아닙니다.",
    "MOVE_PAGE_TITLE": "페이지 이동",
    "PREPARE_PRINTING": "프린트 준비 중입니다. 잠시만 기다려 주세요 ...",
    "START_SLIDESHOW": "슬라이드쇼 시작",
    "STOP_SLIDESHOW": "슬라이드쇼 정지",
    "START_FULLSCREEN": "전체화면 시작",
    "EXIT_FULLSCREEN": "전체화면 종료",
    "ALL_FILES": "전체파일",
    "DEFAULT_FOLDER": "기본폴더",
    "MASTER_FOLDER": "관리자 폴더",
});
