define({
    "OK": "Okay",
    "CANCEL": "Cancel",
    "DELETE": "Delete",
    "BUTTON_YES": "Yes",
    "BUTTON_NO": "No",
    "ERROR": "Error",
    "ALERT_TITLE" : "Alert",
    "ALERT_NO_SEARCH_RESULT": "No results found.",
    "ADD_BOOKMARK_TITILE": "Add Bookmark",
    "REMOVE_BOOKMARK_TITILE": "Remove Bookmark",
    "MODIFY_BOOKMARK_TITILE": "Modify Bookmark",
    "ENTER_TEXT": "Enter text",
    "TEXT_INPUT_PLACEHOLDER": "Enter text",
    "ENTER_SEARCH_WORDS_PLACEHOLDER": "Enter search words ...",
    "ADD_MEMO_TITILE" : "Add Memo",
    "MODIFY_MEMO_TITILE": "Modify Memo",
    "EMPTY": "Empty",
    "SELECT_PAGE_TITLE": "Select page",
    "LEFT_PAGE_TITLE": "Left Page",
    "RIGHT_PAGE_TITLE": "Right Pag",
    "REMOVE_ALL_MY_LIBRARY": "Are you sure you want to delete all of your library?",
    "ERROR_NOT_VALID_PAGE_NUMBER" : "{0} page is not a valid page number.",
    "MOVE_PAGE_TITLE": "Move Page",
    "PREPARE_PRINTING": "Preparing print ...",
    "START_SLIDESHOW": "Start Slideshow",
    "STOP_SLIDESHOW": "Stop Slideshow",
    "START_FULLSCREEN": "Start Fullscreen",
    "EXIT_FULLSCREEN": "Exit Fullscreen",
    "ALL_FILES": "All Files",
    "DEFAULT_FOLDER": "Default Folder",
    "MASTER_FOLDER": "Master Folder",
});
